# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(verbose_name='Действие', default='E', max_length=1, choices=[('E', ''), ('O', 'На согласование'), ('Y', 'Согласовано'), ('N', 'Не согласовано'), ('C', 'Изменение')])),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab1000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб1000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб1000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб1000_Кол3', default=0)),
                ('c4', models.IntegerField(verbose_name='Таб1000_Кол4', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб1000_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб1000_Кол6', default=0)),
                ('c7', models.IntegerField(verbose_name='Таб1000_Кол7', default=0)),
                ('c8', models.IntegerField(verbose_name='Таб1000_Кол8', default=0)),
                ('c9', models.IntegerField(verbose_name='Таб1000_Кол9', default=0)),
                ('c10', models.IntegerField(verbose_name='Таб1000_Кол10', default=0)),
                ('c11', models.IntegerField(verbose_name='Таб1000_Кол11', default=0)),
                ('c12', models.IntegerField(verbose_name='Таб1000_Кол12', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab2000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб2000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб2000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб2000_Кол3', default=0)),
                ('c4', models.IntegerField(verbose_name='Таб2000_Кол4', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab3000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб3000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб3000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб3000_Кол3', default=0)),
                ('c4', models.IntegerField(verbose_name='Таб3000_Кол4', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб3000_Кол5', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab4000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб4000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб4000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб4000_Кол3', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб4000_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб4000_Кол6', default=0)),
                ('c7', models.IntegerField(verbose_name='Таб4000_Кол7', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab5000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб5000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб5000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб5000_Кол3', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб5000_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб5000_Кол6', default=0)),
                ('c7', models.IntegerField(verbose_name='Таб5000_Кол7', default=0)),
                ('c13', models.IntegerField(verbose_name='Таб5000_Кол13', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab5001',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб5001_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб5001_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб5001_Кол3', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб5001_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб5001_Кол6', default=0)),
                ('c7', models.IntegerField(verbose_name='Таб5001_Кол7', default=0)),
                ('c13', models.IntegerField(verbose_name='Таб5001_Кол13', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab6000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб6000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб6000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб6000_Кол3', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб6000_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб6000_Кол6', default=0)),
                ('c7', models.IntegerField(verbose_name='Таб6000_Кол7', default=0)),
                ('c13', models.IntegerField(verbose_name='Таб6000_Кол13', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc3Tab7000',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('c1', models.IntegerField(verbose_name='Таб7000_Кол1', default=0)),
                ('c2', models.IntegerField(verbose_name='Таб7000_Кол2', default=0)),
                ('c3', models.IntegerField(verbose_name='Таб7000_Кол3', default=0)),
                ('c4', models.IntegerField(verbose_name='Таб7000_Кол4', default=0)),
                ('c5', models.IntegerField(verbose_name='Таб7000_Кол5', default=0)),
                ('c6', models.IntegerField(verbose_name='Таб7000_Кол6', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Hosp',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_type',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('name', models.CharField(verbose_name='Наименование', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('status', models.CharField(verbose_name='Статус', default='E', max_length=1, choices=[('E', 'Редактирование'), ('W', 'Согласование'), ('C', 'Корректировка'), ('F', 'Завершено')])),
                ('datef', models.DateField()),
                ('date_mod', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('name', models.CharField(verbose_name='Наименование Краткое', max_length=64)),
                ('name_full', models.CharField(verbose_name='Наименование Полное', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('name', models.CharField(verbose_name='Наименование', max_length=100)),
                ('dateb', models.DateField()),
                ('datee', models.DateField()),
                ('prev', models.ForeignKey(to='medicament.Period', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('name', models.CharField(verbose_name='Регион', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Right_type',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('group', models.ForeignKey(to='auth.Group')),
                ('type', models.ForeignKey(to='medicament.Doc_type')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('contact', models.CharField(null=True, max_length=50, verbose_name='Ответственный', blank=True)),
                ('email', models.EmailField(null=True, max_length=60, verbose_name='Email', blank=True)),
                ('tel', models.CharField(null=True, max_length=20, verbose_name='Телефон', blank=True)),
                ('role', models.CharField(verbose_name='Роль', default='Р', max_length=1, choices=[('Р', 'Редактирование'), ('К', 'Контроль'), ('F', 'Администратор')])),
                ('hosp', models.ForeignKey(to='medicament.Hosp')),
                ('type', models.ForeignKey(to='medicament.Doc_type')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('table', models.CharField(verbose_name='Таблица', max_length=8)),
                ('name', models.CharField(verbose_name='Наименование', max_length=100)),
                ('name1', models.CharField(null=True, max_length=20, verbose_name='Доп.Наименов', blank=True)),
                ('nomer', models.CharField(null=True, max_length=10, verbose_name='Номер', blank=True)),
                ('type', models.ForeignKey(to='medicament.Doc_type')),
            ],
        ),
        migrations.CreateModel(
            name='Synchro',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('name', models.CharField(verbose_name='Наименование Краткое', max_length=16)),
                ('val', models.IntegerField(verbose_name='Знач', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doc1',
            fields=[
                ('document_ptr', models.OneToOneField(primary_key=True, parent_link=True, to='medicament.Document', serialize=False, auto_created=True)),
                ('c1_1', models.IntegerField(verbose_name='Кол1-1', default=0)),
                ('c1_2', models.IntegerField(verbose_name='Кол1-2', default=0)),
                ('c1_3', models.IntegerField(verbose_name='Кол1-3', default=0)),
                ('c1_4', models.IntegerField(verbose_name='Кол1-4', default=0)),
                ('c1_5', models.IntegerField(verbose_name='Кол1-5', default=0)),
                ('c2_6', models.IntegerField(verbose_name='Кол2-6', default=0)),
                ('c2_7', models.IntegerField(verbose_name='Кол2-7', default=0)),
                ('c2_8', models.IntegerField(verbose_name='Кол2-8', default=0)),
                ('c3_1', models.IntegerField(verbose_name='КолПр3-1', default=0)),
                ('c3_2', models.IntegerField(verbose_name='КолПр3-2', default=0)),
                ('c3_3', models.IntegerField(verbose_name='КолПр3-3', default=0)),
                ('c3_4', models.IntegerField(verbose_name='КолПр3-4', default=0)),
                ('c3_5', models.IntegerField(verbose_name='КолПр3-5', default=0)),
                ('c3_6', models.IntegerField(verbose_name='КолПр3-6', default=0)),
                ('c3_7', models.IntegerField(verbose_name='КолПр3-7', default=0)),
                ('c3_8', models.IntegerField(verbose_name='КолПр3-8', default=0)),
                ('c4_1', models.IntegerField(verbose_name='Кол4-1', default=0)),
                ('c4_2', models.IntegerField(verbose_name='Кол4-2', default=0)),
                ('c4_3', models.IntegerField(verbose_name='Кол4-3', default=0)),
                ('c4_4', models.IntegerField(verbose_name='Кол4-4', default=0)),
                ('c4_5', models.IntegerField(verbose_name='Кол4-5', default=0)),
                ('c4_6', models.IntegerField(verbose_name='Кол4-6', default=0)),
                ('c4_7', models.IntegerField(verbose_name='Кол4-7', default=0)),
                ('c4_8', models.IntegerField(verbose_name='Кол4-8', default=0)),
            ],
            bases=('medicament.document',),
        ),
        migrations.CreateModel(
            name='Doc2',
            fields=[
                ('document_ptr', models.OneToOneField(primary_key=True, parent_link=True, to='medicament.Document', serialize=False, auto_created=True)),
                ('c2_1', models.IntegerField(verbose_name='Кол2_1', default=0)),
                ('c2_2', models.IntegerField(verbose_name='Кол2_2', default=0)),
                ('c2_3', models.IntegerField(verbose_name='Кол2_3', default=0)),
                ('c2_3_1', models.IntegerField(verbose_name='Кол2_3_1', default=0)),
                ('c2_3_2', models.IntegerField(verbose_name='Кол2_3_2', default=0)),
                ('c2_3_3', models.IntegerField(verbose_name='Кол2_3_3', default=0)),
                ('c2_4', models.IntegerField(verbose_name='Кол2_4', default=0)),
                ('c2_4_1', models.IntegerField(verbose_name='Кол2_4_1', default=0)),
                ('c2_4_2', models.IntegerField(verbose_name='Кол2_4_2', default=0)),
                ('c2_4_3', models.IntegerField(verbose_name='Кол2_4_3', default=0)),
                ('c2_5', models.IntegerField(verbose_name='Кол2_5', default=0)),
                ('c2_5_1', models.IntegerField(verbose_name='Кол2_5_1', default=0)),
                ('c2_5_2', models.IntegerField(verbose_name='Кол2_5_2', default=0)),
                ('c2_5_3', models.IntegerField(verbose_name='Кол2_5_3', default=0)),
                ('c2_5_4', models.IntegerField(verbose_name='Кол2_5_4', default=0)),
                ('c2_5_5', models.IntegerField(verbose_name='Кол2_5_5', default=0)),
                ('c2_5_6', models.IntegerField(verbose_name='Кол2_5_6', default=0)),
                ('c2_5_7', models.IntegerField(verbose_name='Кол2_5_7', default=0)),
                ('c2_5_8', models.IntegerField(verbose_name='Кол2_5_8', default=0)),
                ('c2_5_9', models.IntegerField(verbose_name='Кол2_5_9', default=0)),
                ('c2_5_10', models.FloatField(verbose_name='Кол2_5_10', default=0)),
                ('c2_5_11', models.FloatField(verbose_name='Кол2_5_11', default=0)),
                ('c2_5_12', models.FloatField(verbose_name='Кол2_5_12', default=0)),
                ('c2_5_13', models.IntegerField(verbose_name='Кол2_5_13', default=0)),
                ('c2_5_14', models.IntegerField(verbose_name='Кол2_5_14', default=0)),
                ('c2_5_15', models.IntegerField(verbose_name='Кол2_5_15', default=0)),
                ('c2_5_16', models.IntegerField(verbose_name='Кол2_5_16', default=0)),
                ('c2_5_17', models.IntegerField(verbose_name='Кол2_5_17', default=0)),
                ('c2_5_18', models.IntegerField(verbose_name='Кол2_5_18', default=0)),
                ('c2_5_19', models.IntegerField(verbose_name='Кол2_5_19', default=0)),
                ('c2_5_20', models.IntegerField(verbose_name='Кол2_5_20', default=0)),
                ('c2_5_21', models.IntegerField(verbose_name='Кол2_5_21', default=0)),
                ('c2_5_22', models.IntegerField(verbose_name='Кол2_5_22', default=0)),
                ('c2_5_23', models.IntegerField(verbose_name='Кол2_5_23', default=0)),
                ('c2_5_24', models.IntegerField(verbose_name='Кол2_5_24', default=0)),
                ('c2_5_25', models.IntegerField(verbose_name='Кол2_5_25', default=0)),
                ('c2_5_26', models.IntegerField(verbose_name='Кол2_5_26', default=0)),
                ('c2_5_27', models.IntegerField(verbose_name='Кол2_5_27', default=0)),
                ('c2_5_28', models.IntegerField(verbose_name='Кол2_5_28', default=0)),
                ('c2_5_29', models.IntegerField(verbose_name='Кол2_5_29', default=0)),
                ('c2_5_30', models.IntegerField(verbose_name='Кол2_5_30', default=0)),
                ('c2_5_31', models.IntegerField(verbose_name='Кол2_5_31', default=0)),
                ('c2_5_32', models.IntegerField(verbose_name='Кол2_5_32', default=0)),
                ('c2_5_33', models.IntegerField(verbose_name='Кол2_5_33', default=0)),
                ('c2_5_34', models.IntegerField(verbose_name='Кол2_5_34', default=0)),
                ('c2_5_35', models.IntegerField(verbose_name='Кол2_5_35', default=0)),
                ('c2_5_36', models.IntegerField(verbose_name='Кол2_5_36', default=0)),
                ('c2_5_37', models.IntegerField(verbose_name='Кол2_5_37', default=0)),
                ('c2_5_38', models.IntegerField(verbose_name='Кол2_5_38', default=0)),
                ('c2_5_39', models.IntegerField(verbose_name='Кол2_5_39', default=0)),
                ('c2_5_40', models.IntegerField(verbose_name='Кол2_5_40', default=0)),
                ('c2_5_41', models.IntegerField(verbose_name='Кол2_5_41', default=0)),
                ('c2_6', models.IntegerField(verbose_name='Кол2_6', default=0)),
                ('c2_7', models.IntegerField(verbose_name='Кол2_7', default=0)),
                ('c2_8', models.FloatField(verbose_name='Кол2_8', default=0)),
                ('c2_9', models.IntegerField(verbose_name='Кол2_9', default=0)),
                ('c2_10', models.FloatField(verbose_name='Кол2_10', default=0)),
                ('c2_11', models.FloatField(verbose_name='Кол2_11', default=0)),
                ('c2_12', models.FloatField(verbose_name='Кол2_12', default=0)),
                ('c2_13', models.IntegerField(verbose_name='Кол2_13', default=0)),
                ('c2_13_1', models.IntegerField(verbose_name='Кол2_13_1', default=0)),
                ('c2_13_2', models.IntegerField(verbose_name='Кол2_13_2', default=0)),
                ('c2_13_3', models.IntegerField(verbose_name='Кол2_13_3', default=0)),
                ('c2_13_4', models.IntegerField(verbose_name='Кол2_13_4', default=0)),
                ('c2_13_5', models.IntegerField(verbose_name='Кол2_13_5', default=0)),
                ('c2_13_6', models.IntegerField(verbose_name='Кол2_13_6', default=0)),
                ('c2_13_7', models.IntegerField(verbose_name='Кол2_13_7', default=0)),
                ('c2_13_8', models.IntegerField(verbose_name='Кол2_13_8', default=0)),
                ('c2_13_9', models.IntegerField(verbose_name='Кол2_13_9', default=0)),
                ('c2_13_10', models.IntegerField(verbose_name='Кол2_13_10', default=0)),
                ('c2_13_11', models.IntegerField(verbose_name='Кол2_13_11', default=0)),
                ('c2_13_12', models.IntegerField(verbose_name='Кол2_13_12', default=0)),
                ('c2_13_13', models.IntegerField(verbose_name='Кол2_13_13', default=0)),
                ('c2_13_14', models.IntegerField(verbose_name='Кол2_13_14', default=0)),
                ('c2_13_15', models.IntegerField(verbose_name='Кол2_13_15', default=0)),
                ('c2_13_16', models.IntegerField(verbose_name='Кол2_13_16', default=0)),
                ('c2_13_17', models.IntegerField(verbose_name='Кол2_13_17', default=0)),
                ('c2_13_18', models.IntegerField(verbose_name='Кол2_13_18', default=0)),
                ('c2_13_19', models.IntegerField(verbose_name='Кол2_13_19', default=0)),
                ('c2_13_20', models.IntegerField(verbose_name='Кол2_13_20', default=0)),
                ('c2_13_21', models.IntegerField(verbose_name='Кол2_13_21', default=0)),
                ('c2_13_22', models.IntegerField(verbose_name='Кол2_13_22', default=0)),
                ('c2_13_23', models.IntegerField(verbose_name='Кол2_13_23', default=0)),
                ('c2_13_24', models.IntegerField(verbose_name='Кол2_13_24', default=0)),
                ('c2_13_25', models.IntegerField(verbose_name='Кол2_13_25', default=0)),
                ('c2_13_26', models.IntegerField(verbose_name='Кол2_13_26', default=0)),
                ('c2_13_27', models.IntegerField(verbose_name='Кол2_13_27', default=0)),
                ('c2_13_28', models.IntegerField(verbose_name='Кол2_13_28', default=0)),
                ('c2_13_29', models.IntegerField(verbose_name='Кол2_13_29', default=0)),
                ('c2_13_30', models.IntegerField(verbose_name='Кол2_13_30', default=0)),
                ('c2_13_31', models.IntegerField(verbose_name='Кол2_13_31', default=0)),
                ('c2_13_32', models.IntegerField(verbose_name='Кол2_13_32', default=0)),
                ('c2_13_33', models.IntegerField(verbose_name='Кол2_13_33', default=0)),
                ('c2_13_34', models.IntegerField(verbose_name='Кол2_13_34', default=0)),
                ('c2_13_35', models.IntegerField(verbose_name='Кол2_13_35', default=0)),
                ('c2_13_36', models.IntegerField(verbose_name='Кол2_13_36', default=0)),
                ('c2_13_37', models.IntegerField(verbose_name='Кол2_13_37', default=0)),
                ('c2_13_38', models.IntegerField(verbose_name='Кол2_13_38', default=0)),
                ('c2_13_39', models.IntegerField(verbose_name='Кол2_13_39', default=0)),
                ('c2_13_40', models.IntegerField(verbose_name='Кол2_13_40', default=0)),
                ('c2_13_41', models.IntegerField(verbose_name='Кол2_13_41', default=0)),
                ('c2_13_42', models.IntegerField(verbose_name='Кол2_13_42', default=0)),
                ('c2_13_43', models.IntegerField(verbose_name='Кол2_13_43', default=0)),
                ('c2_13_44', models.IntegerField(verbose_name='Кол2_13_44', default=0)),
                ('c2_13_45', models.IntegerField(verbose_name='Кол2_13_45', default=0)),
                ('c2_13_46', models.IntegerField(verbose_name='Кол2_13_46', default=0)),
                ('c2_13_47', models.IntegerField(verbose_name='Кол2_13_47', default=0)),
                ('c2_13_48', models.IntegerField(verbose_name='Кол2_13_48', default=0)),
                ('c2_13_49', models.IntegerField(verbose_name='Кол2_13_49', default=0)),
                ('c2_13_50', models.IntegerField(verbose_name='Кол2_13_50', default=0)),
                ('c2_13_51', models.IntegerField(verbose_name='Кол2_13_51', default=0)),
                ('c2_13_52', models.IntegerField(verbose_name='Кол2_13_52', default=0)),
                ('c2_13_53', models.IntegerField(verbose_name='Кол2_13_53', default=0)),
                ('c2_13_54', models.IntegerField(verbose_name='Кол2_13_54', default=0)),
                ('c2_13_55', models.IntegerField(verbose_name='Кол2_13_55', default=0)),
                ('c2_13_56', models.IntegerField(verbose_name='Кол2_13_56', default=0)),
                ('c2_13_57', models.IntegerField(verbose_name='Кол2_13_57', default=0)),
                ('c2_13_58', models.IntegerField(verbose_name='Кол2_13_58', default=0)),
                ('c2_13_59', models.IntegerField(verbose_name='Кол2_13_59', default=0)),
                ('c2_13_60', models.IntegerField(verbose_name='Кол2_13_60', default=0)),
                ('c2_13_61', models.IntegerField(verbose_name='Кол2_13_61', default=0)),
                ('c2_13_62', models.IntegerField(verbose_name='Кол2_13_62', default=0)),
                ('c2_13_63', models.IntegerField(verbose_name='Кол2_13_63', default=0)),
                ('c2_13_64', models.IntegerField(verbose_name='Кол2_13_64', default=0)),
                ('c2_13_65', models.IntegerField(verbose_name='Кол2_13_65', default=0)),
                ('c2_13_66', models.IntegerField(verbose_name='Кол2_13_66', default=0)),
                ('c2_13_67', models.IntegerField(verbose_name='Кол2_13_67', default=0)),
                ('c2_13_68', models.IntegerField(verbose_name='Кол2_13_68', default=0)),
                ('c2_13_69', models.IntegerField(verbose_name='Кол2_13_69', default=0)),
                ('c2_13_70', models.IntegerField(verbose_name='Кол2_13_70', default=0)),
                ('c2_13_71', models.IntegerField(verbose_name='Кол2_13_71', default=0)),
                ('c2_13_72', models.IntegerField(verbose_name='Кол2_13_72', default=0)),
                ('c2_13_73', models.IntegerField(verbose_name='Кол2_13_73', default=0)),
                ('c2_13_74', models.IntegerField(verbose_name='Кол2_13_74', default=0)),
                ('c2_13_75', models.IntegerField(verbose_name='Кол2_13_75', default=0)),
                ('c2_13_76', models.IntegerField(verbose_name='Кол2_13_76', default=0)),
                ('c2_13_77', models.IntegerField(verbose_name='Кол2_13_77', default=0)),
                ('c2_13_78', models.IntegerField(verbose_name='Кол2_13_78', default=0)),
                ('c2_13_79', models.IntegerField(verbose_name='Кол2_13_79', default=0)),
                ('c2_13_80', models.IntegerField(verbose_name='Кол2_13_80', default=0)),
                ('c2_13_81', models.IntegerField(verbose_name='Кол2_13_81', default=0)),
                ('c2_13_82', models.IntegerField(verbose_name='Кол2_13_82', default=0)),
                ('c2_13_83', models.IntegerField(verbose_name='Кол2_13_83', default=0)),
                ('c2_13_84', models.IntegerField(verbose_name='Кол2_13_84', default=0)),
                ('c2_13_85', models.IntegerField(verbose_name='Кол2_13_85', default=0)),
                ('c2_13_86', models.IntegerField(verbose_name='Кол2_13_86', default=0)),
                ('c2_13_87', models.IntegerField(verbose_name='Кол2_13_87', default=0)),
                ('c2_13_88', models.IntegerField(verbose_name='Кол2_13_88', default=0)),
                ('c2_13_89', models.IntegerField(verbose_name='Кол2_13_89', default=0)),
                ('c2_13_90', models.IntegerField(verbose_name='Кол2_13_90', default=0)),
                ('c2_13_91', models.IntegerField(verbose_name='Кол2_13_91', default=0)),
                ('c2_13_92', models.IntegerField(verbose_name='Кол2_13_92', default=0)),
                ('c2_13_93', models.IntegerField(verbose_name='Кол2_13_93', default=0)),
                ('c2_13_94', models.IntegerField(verbose_name='Кол2_13_94', default=0)),
                ('c2_13_95', models.IntegerField(verbose_name='Кол2_13_95', default=0)),
                ('c2_13_96', models.IntegerField(verbose_name='Кол2_13_96', default=0)),
                ('c2_13_97', models.IntegerField(verbose_name='Кол2_13_97', default=0)),
                ('c2_13_98', models.IntegerField(verbose_name='Кол2_13_98', default=0)),
                ('c2_13_99', models.IntegerField(verbose_name='Кол2_13_99', default=0)),
                ('c2_13_100', models.IntegerField(verbose_name='Кол2_13_100', default=0)),
                ('c2_13_101', models.IntegerField(verbose_name='Кол2_13_101', default=0)),
                ('c2_13_102', models.IntegerField(verbose_name='Кол2_13_102', default=0)),
                ('c2_13_103', models.IntegerField(verbose_name='Кол2_13_103', default=0)),
                ('c2_13_104', models.IntegerField(verbose_name='Кол2_13_104', default=0)),
                ('c2_13_105', models.IntegerField(verbose_name='Кол2_13_105', default=0)),
                ('c2_13_106', models.IntegerField(verbose_name='Кол2_13_106', default=0)),
                ('c2_13_107', models.IntegerField(verbose_name='Кол2_13_107', default=0)),
                ('c2_13_108', models.IntegerField(verbose_name='Кол2_13_108', default=0)),
                ('c2_13_109', models.IntegerField(verbose_name='Кол2_13_109', default=0)),
                ('c2_13_110', models.IntegerField(verbose_name='Кол2_13_110', default=0)),
                ('c2_13_111', models.IntegerField(verbose_name='Кол2_13_111', default=0)),
                ('c2_13_112', models.IntegerField(verbose_name='Кол2_13_112', default=0)),
                ('c2_13_113', models.IntegerField(verbose_name='Кол2_13_113', default=0)),
                ('c2_13_114', models.IntegerField(verbose_name='Кол2_13_114', default=0)),
                ('c2_13_115', models.IntegerField(verbose_name='Кол2_13_115', default=0)),
                ('c2_13_116', models.IntegerField(verbose_name='Кол2_13_116', default=0)),
                ('c2_13_117', models.IntegerField(verbose_name='Кол2_13_117', default=0)),
                ('c2_13_118', models.IntegerField(verbose_name='Кол2_13_118', default=0)),
                ('c2_13_119', models.IntegerField(verbose_name='Кол2_13_119', default=0)),
                ('c2_13_120', models.IntegerField(verbose_name='Кол2_13_120', default=0)),
                ('c2_13_121', models.IntegerField(verbose_name='Кол2_13_121', default=0)),
                ('c2_13_122', models.IntegerField(verbose_name='Кол2_13_122', default=0)),
                ('c2_13_123', models.IntegerField(verbose_name='Кол2_13_123', default=0)),
                ('c2_13_124', models.IntegerField(verbose_name='Кол2_13_124', default=0)),
                ('c2_14', models.IntegerField(verbose_name='Кол2_14', default=0)),
                ('c2_14_1', models.IntegerField(verbose_name='Кол2_14_1', default=0)),
                ('c2_14_2', models.IntegerField(verbose_name='Кол2_14_2', default=0)),
                ('c2_14_3', models.IntegerField(verbose_name='Кол2_14_3', default=0)),
                ('c2_14_4', models.IntegerField(verbose_name='Кол2_14_4', default=0)),
                ('c2_14_5', models.IntegerField(verbose_name='Кол2_14_5', default=0)),
                ('c2_14_6', models.IntegerField(verbose_name='Кол2_14_6', default=0)),
                ('c2_14_7', models.IntegerField(verbose_name='Кол2_14_7', default=0)),
                ('c2_14_8', models.IntegerField(verbose_name='Кол2_14_8', default=0)),
                ('c2_14_9', models.IntegerField(verbose_name='Кол2_14_9', default=0)),
                ('c2_14_10', models.IntegerField(verbose_name='Кол2_14_10', default=0)),
                ('c2_14_11', models.IntegerField(verbose_name='Кол2_14_11', default=0)),
                ('c2_14_12', models.IntegerField(verbose_name='Кол2_14_12', default=0)),
                ('c2_14_13', models.IntegerField(verbose_name='Кол2_14_13', default=0)),
                ('c2_14_14', models.IntegerField(verbose_name='Кол2_14_14', default=0)),
                ('c2_14_15', models.IntegerField(verbose_name='Кол2_14_15', default=0)),
                ('c2_14_16', models.IntegerField(verbose_name='Кол2_14_16', default=0)),
                ('c2_14_17', models.IntegerField(verbose_name='Кол2_14_17', default=0)),
                ('c2_14_18', models.IntegerField(verbose_name='Кол2_14_18', default=0)),
                ('c2_14_19', models.IntegerField(verbose_name='Кол2_14_19', default=0)),
                ('c2_14_20', models.IntegerField(verbose_name='Кол2_14_20', default=0)),
                ('c2_14_21', models.IntegerField(verbose_name='Кол2_14_21', default=0)),
                ('c2_14_22', models.IntegerField(verbose_name='Кол2_14_22', default=0)),
                ('c2_14_23', models.IntegerField(verbose_name='Кол2_14_23', default=0)),
                ('c2_14_24', models.IntegerField(verbose_name='Кол2_14_24', default=0)),
                ('c2_14_25', models.IntegerField(verbose_name='Кол2_14_25', default=0)),
                ('c2_14_26', models.IntegerField(verbose_name='Кол2_14_26', default=0)),
                ('c2_14_27', models.IntegerField(verbose_name='Кол2_14_27', default=0)),
                ('c2_14_28', models.IntegerField(verbose_name='Кол2_14_28', default=0)),
                ('c2_14_29', models.IntegerField(verbose_name='Кол2_14_29', default=0)),
                ('c2_14_30', models.IntegerField(verbose_name='Кол2_14_30', default=0)),
                ('c2_14_31', models.IntegerField(verbose_name='Кол2_14_31', default=0)),
                ('c2_14_32', models.IntegerField(verbose_name='Кол2_14_32', default=0)),
                ('c2_14_33', models.IntegerField(verbose_name='Кол2_14_33', default=0)),
                ('c2_14_34', models.IntegerField(verbose_name='Кол2_14_34', default=0)),
                ('c2_14_35', models.IntegerField(verbose_name='Кол2_14_35', default=0)),
                ('c2_14_36', models.IntegerField(verbose_name='Кол2_14_36', default=0)),
                ('c2_14_37', models.IntegerField(verbose_name='Кол2_14_37', default=0)),
                ('c2_14_38', models.IntegerField(verbose_name='Кол2_14_38', default=0)),
                ('c2_14_39', models.IntegerField(verbose_name='Кол2_14_39', default=0)),
                ('c2_14_40', models.IntegerField(verbose_name='Кол2_14_40', default=0)),
                ('c2_14_41', models.IntegerField(verbose_name='Кол2_14_41', default=0)),
                ('c2_14_42', models.IntegerField(verbose_name='Кол2_14_42', default=0)),
                ('c2_14_43', models.IntegerField(verbose_name='Кол2_14_43', default=0)),
                ('c2_14_44', models.IntegerField(verbose_name='Кол2_14_44', default=0)),
                ('c2_14_45', models.IntegerField(verbose_name='Кол2_14_45', default=0)),
                ('c2_15', models.IntegerField(verbose_name='Кол2_15', default=0)),
                ('c2_16', models.IntegerField(verbose_name='Кол2_16', default=0)),
                ('c2_17', models.IntegerField(verbose_name='Кол2_17', default=0)),
                ('c2_18', models.IntegerField(verbose_name='Кол2_18', default=0)),
                ('c2_19', models.IntegerField(verbose_name='Кол2_19', default=0)),
                ('c2_20', models.IntegerField(verbose_name='Кол2_20', default=0)),
                ('c2_21', models.FloatField(verbose_name='Кол2_21', default=0)),
                ('c2_22', models.FloatField(verbose_name='Кол2_22', default=0)),
                ('c2_23', models.FloatField(verbose_name='Кол2_23', default=0)),
                ('c2_24', models.FloatField(verbose_name='Кол2_24', default=0)),
                ('c2_25', models.FloatField(verbose_name='Кол2_25', default=0)),
                ('c2_26', models.FloatField(verbose_name='Кол2_26', default=0)),
                ('c2_27', models.IntegerField(verbose_name='Кол2_27', default=0)),
                ('c2_28', models.IntegerField(verbose_name='Кол2_28', default=0)),
                ('c3_1', models.IntegerField(verbose_name='Кол3_1', default=0)),
                ('c3_2', models.IntegerField(verbose_name='Кол3_2', default=0)),
                ('c3_3', models.IntegerField(verbose_name='Кол3_3', default=0)),
                ('c3_4', models.IntegerField(verbose_name='Кол3_4', default=0)),
                ('c3_5', models.IntegerField(verbose_name='Кол3_5', default=0)),
                ('c3_6', models.IntegerField(verbose_name='Кол3_6', default=0)),
                ('c3_7', models.IntegerField(verbose_name='Кол3_7', default=0)),
                ('c3_8', models.IntegerField(verbose_name='Кол3_8', default=0)),
                ('c3_9', models.IntegerField(verbose_name='Кол3_9', default=0)),
                ('c3_10', models.IntegerField(verbose_name='Кол3_10', default=0)),
                ('c3_11', models.IntegerField(verbose_name='Кол3_11', default=0)),
                ('c3_12', models.IntegerField(verbose_name='Кол3_12', default=0)),
                ('c3_13', models.IntegerField(verbose_name='Кол3_13', default=0)),
                ('c3_14', models.IntegerField(verbose_name='Кол3_14', default=0)),
                ('c3_15', models.IntegerField(verbose_name='Кол3_15', default=0)),
                ('c3_16', models.IntegerField(verbose_name='Кол3_16', default=0)),
                ('c3_17', models.IntegerField(verbose_name='Кол3_17', default=0)),
                ('c3_18', models.IntegerField(verbose_name='Кол3_18', default=0)),
                ('c3_19', models.IntegerField(verbose_name='Кол3_19', default=0)),
                ('c3_20', models.IntegerField(verbose_name='Кол3_20', default=0)),
                ('c3_21', models.IntegerField(verbose_name='Кол3_21', default=0)),
                ('c3_22', models.IntegerField(verbose_name='Кол3_22', default=0)),
                ('c3_23', models.IntegerField(verbose_name='Кол3_23', default=0)),
                ('c3_24', models.IntegerField(verbose_name='Кол3_24', default=0)),
                ('c3_25', models.IntegerField(verbose_name='Кол3_25', default=0)),
                ('c3_26', models.IntegerField(verbose_name='Кол3_26', default=0)),
                ('c3_27', models.IntegerField(verbose_name='Кол3_27', default=0)),
                ('c3_28', models.IntegerField(verbose_name='Кол3_28', default=0)),
                ('c3_29', models.IntegerField(verbose_name='Кол3_29', default=0)),
                ('c3_30', models.IntegerField(verbose_name='Кол3_30', default=0)),
                ('c3_31', models.IntegerField(verbose_name='Кол3_31', default=0)),
                ('c3_32', models.IntegerField(verbose_name='Кол3_32', default=0)),
                ('c3_33', models.IntegerField(verbose_name='Кол3_33', default=0)),
                ('c3_34', models.IntegerField(verbose_name='Кол3_34', default=0)),
                ('c3_35', models.IntegerField(verbose_name='Кол3_35', default=0)),
                ('c3_36', models.IntegerField(verbose_name='Кол3_36', default=0)),
                ('c3_37', models.IntegerField(verbose_name='Кол3_37', default=0)),
                ('c3_38', models.IntegerField(verbose_name='Кол3_38', default=0)),
                ('c4_1', models.IntegerField(verbose_name='Кол4_1', default=0)),
                ('c4_2', models.IntegerField(verbose_name='Кол4_2', default=0)),
                ('c4_3', models.IntegerField(verbose_name='Кол4_3', default=0)),
                ('c4_4', models.IntegerField(verbose_name='Кол4_4', default=0)),
                ('c4_5', models.IntegerField(verbose_name='Кол4_5', default=0)),
                ('c4_6', models.IntegerField(verbose_name='Кол4_6', default=0)),
                ('c4_7', models.IntegerField(verbose_name='Кол4_7', default=0)),
                ('c4_8', models.IntegerField(verbose_name='Кол4_8', default=0)),
                ('c4_9', models.IntegerField(verbose_name='Кол4_9', default=0)),
                ('c4_10', models.IntegerField(verbose_name='Кол4_10', default=0)),
                ('c4_11', models.IntegerField(verbose_name='Кол4_11', default=0)),
                ('c4_12', models.IntegerField(verbose_name='Кол4_12', default=0)),
                ('c4_13', models.IntegerField(verbose_name='Кол4_13', default=0)),
                ('c4_14', models.IntegerField(verbose_name='Кол4_14', default=0)),
                ('c4_15', models.IntegerField(verbose_name='Кол4_15', default=0)),
                ('p3_1', models.CharField(null=True, max_length=80, verbose_name='КолПр3_1', blank=True)),
                ('p3_2', models.CharField(null=True, max_length=80, verbose_name='КолПр3_2', blank=True)),
                ('p3_3', models.CharField(null=True, max_length=80, verbose_name='КолПр3_3', blank=True)),
                ('p3_4', models.CharField(null=True, max_length=80, verbose_name='КолПр3_4', blank=True)),
                ('p3_5', models.CharField(null=True, max_length=80, verbose_name='КолПр3_5', blank=True)),
                ('p3_6', models.CharField(null=True, max_length=80, verbose_name='КолПр3_6', blank=True)),
                ('p3_7', models.CharField(null=True, max_length=80, verbose_name='КолПр3_7', blank=True)),
                ('p3_8', models.CharField(null=True, max_length=80, verbose_name='КолПр3_8', blank=True)),
                ('p3_9', models.CharField(null=True, max_length=80, verbose_name='КолПр3_9', blank=True)),
                ('p3_10', models.CharField(null=True, max_length=80, verbose_name='КолПр3_10', blank=True)),
                ('p3_11', models.CharField(null=True, max_length=80, verbose_name='КолПр3_11', blank=True)),
                ('p3_12', models.CharField(null=True, max_length=80, verbose_name='КолПр3_12', blank=True)),
                ('p3_13', models.CharField(null=True, max_length=80, verbose_name='КолПр3_13', blank=True)),
                ('p3_14', models.CharField(null=True, max_length=80, verbose_name='КолПр3_14', blank=True)),
                ('p3_15', models.CharField(null=True, max_length=80, verbose_name='КолПр3_15', blank=True)),
                ('p3_16', models.CharField(null=True, max_length=80, verbose_name='КолПр3_16', blank=True)),
                ('p3_17', models.CharField(null=True, max_length=80, verbose_name='КолПр3_17', blank=True)),
                ('p3_18', models.CharField(null=True, max_length=80, verbose_name='КолПр3_18', blank=True)),
                ('p3_19', models.CharField(null=True, max_length=80, verbose_name='КолПр3_19', blank=True)),
                ('p3_20', models.CharField(null=True, max_length=80, verbose_name='КолПр3_20', blank=True)),
                ('p3_21', models.CharField(null=True, max_length=80, verbose_name='КолПр3_21', blank=True)),
                ('p3_22', models.CharField(null=True, max_length=80, verbose_name='КолПр3_22', blank=True)),
                ('p3_23', models.CharField(null=True, max_length=80, verbose_name='КолПр3_23', blank=True)),
                ('p3_24', models.CharField(null=True, max_length=80, verbose_name='КолПр3_24', blank=True)),
                ('p3_25', models.CharField(null=True, max_length=80, verbose_name='КолПр3_25', blank=True)),
                ('p3_26', models.CharField(null=True, max_length=80, verbose_name='КолПр3_26', blank=True)),
                ('p3_27', models.CharField(null=True, max_length=80, verbose_name='КолПр3_27', blank=True)),
                ('p3_28', models.CharField(null=True, max_length=80, verbose_name='КолПр3_28', blank=True)),
                ('p3_29', models.CharField(null=True, max_length=80, verbose_name='КолПр3_29', blank=True)),
                ('p3_30', models.CharField(null=True, max_length=80, verbose_name='КолПр3_30', blank=True)),
                ('p3_31', models.CharField(null=True, max_length=80, verbose_name='КолПр3_31', blank=True)),
                ('p3_32', models.CharField(null=True, max_length=80, verbose_name='КолПр3_32', blank=True)),
                ('p3_33', models.CharField(null=True, max_length=80, verbose_name='КолПр3_33', blank=True)),
                ('p3_34', models.CharField(null=True, max_length=80, verbose_name='КолПр3_34', blank=True)),
                ('p3_35', models.CharField(null=True, max_length=80, verbose_name='КолПр3_35', blank=True)),
                ('p3_36', models.CharField(null=True, max_length=80, verbose_name='КолПр3_36', blank=True)),
                ('p3_37', models.CharField(null=True, max_length=80, verbose_name='КолПр3_37', blank=True)),
                ('p3_38', models.CharField(null=True, max_length=80, verbose_name='КолПр3_38', blank=True)),
            ],
            bases=('medicament.document',),
        ),
        migrations.CreateModel(
            name='Doc3',
            fields=[
                ('document_ptr', models.OneToOneField(primary_key=True, parent_link=True, to='medicament.Document', serialize=False, auto_created=True)),
                ('t3001', models.IntegerField(verbose_name='Таб3001', default=0)),
                ('t4001_r1', models.IntegerField(verbose_name='Таб4001_1', default=0)),
                ('t4001_r2', models.IntegerField(verbose_name='Таб4001_2', default=0)),
                ('t4002_r1', models.IntegerField(verbose_name='Таб4002_1', default=0)),
                ('t4002_r2', models.IntegerField(verbose_name='Таб4002_2', default=0)),
                ('t7001', models.IntegerField(verbose_name='Таб7001', default=0)),
                ('t7002', models.IntegerField(verbose_name='Таб7002', default=0)),
                ('t7003', models.IntegerField(verbose_name='Таб7003', default=0)),
                ('t7004', models.IntegerField(verbose_name='Таб7004', default=0)),
                ('t7004_r1', models.IntegerField(verbose_name='Таб7004_1', default=0)),
                ('t7004_r2', models.IntegerField(verbose_name='Таб7004_2', default=0)),
                ('t7004_r3', models.IntegerField(verbose_name='Таб7004_3', default=0)),
                ('t7004_r4', models.IntegerField(verbose_name='Таб7004_4', default=0)),
                ('t7004_r5', models.IntegerField(verbose_name='Таб7004_5', default=0)),
                ('t7004_r6', models.IntegerField(verbose_name='Таб7004_6', default=0)),
                ('t7004_r7', models.IntegerField(verbose_name='Таб7004_7', default=0)),
                ('t7004_r8', models.IntegerField(verbose_name='Таб7004_8', default=0)),
                ('t7005', models.IntegerField(verbose_name='Таб7005', default=0)),
                ('t7006', models.IntegerField(verbose_name='Таб7006', default=0)),
                ('t7006_r1', models.IntegerField(verbose_name='Таб7006_1', default=0)),
                ('t7007', models.IntegerField(verbose_name='Таб7007', default=0)),
                ('t7008', models.IntegerField(verbose_name='Таб7008', default=0)),
                ('t7009', models.IntegerField(verbose_name='Таб7009', default=0)),
                ('t7010', models.IntegerField(verbose_name='Таб7010', default=0)),
                ('t7011', models.IntegerField(verbose_name='Таб7011', default=0)),
                ('t7012', models.IntegerField(verbose_name='Таб7012', default=0)),
            ],
            bases=('medicament.document',),
        ),
        migrations.AddField(
            model_name='hosp',
            name='region',
            field=models.ForeignKey(to='medicament.Region', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hosp',
            field=models.ForeignKey(to='medicament.Hosp'),
        ),
        migrations.AddField(
            model_name='document',
            name='period',
            field=models.ForeignKey(to='medicament.Period'),
        ),
        migrations.AddField(
            model_name='doc_hosp',
            name='doc_type',
            field=models.ForeignKey(to='medicament.Doc_type'),
        ),
        migrations.AddField(
            model_name='doc_hosp',
            name='hosp',
            field=models.ForeignKey(to='medicament.Hosp'),
        ),
        migrations.AddField(
            model_name='doc3tab7000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab6000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab5001',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab5000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab4000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab3000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab2000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='doc3tab1000',
            name='row',
            field=models.ForeignKey(to='medicament.Rows'),
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(to='medicament.Document'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doc3tab7000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab6000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab5001',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab5000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab4000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab3000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab2000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
        migrations.AddField(
            model_name='doc3tab1000',
            name='doc',
            field=models.ForeignKey(to='medicament.Doc3'),
        ),
    ]
