# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('E', ''), ('O', 'На согласование'), ('Y', 'Согласовано'), ('N', 'Не согласовано')], max_length=1, default='E', verbose_name='Действие')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Doc_Hosp',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Doc_type',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Редактирование'), ('W', 'Согласование'), ('C', 'Корректировка'), ('F', 'Завершено')], max_length=1, default='E', verbose_name='Статус')),
                ('datef', models.DateField()),
                ('date_mod', models.DateTimeField(auto_now_add=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Doc2',
            fields=[
                ('document_ptr', models.OneToOneField(serialize=False, primary_key=True, auto_created=True, to='medicament.Document', parent_link=True)),
                ('c2_1', models.IntegerField(default=0, verbose_name='Кол2_1')),
                ('c2_2', models.IntegerField(default=0, verbose_name='Кол2_2')),
                ('c2_3', models.IntegerField(default=0, verbose_name='Кол2_3')),
                ('c2_3_1', models.IntegerField(default=0, verbose_name='Кол2_3_1')),
                ('c2_3_2', models.IntegerField(default=0, verbose_name='Кол2_3_2')),
                ('c2_3_3', models.IntegerField(default=0, verbose_name='Кол2_3_3')),
                ('c2_4', models.IntegerField(default=0, verbose_name='Кол2_4')),
                ('c2_4_1', models.IntegerField(default=0, verbose_name='Кол2_4_1')),
                ('c2_4_2', models.IntegerField(default=0, verbose_name='Кол2_4_2')),
                ('c2_4_3', models.IntegerField(default=0, verbose_name='Кол2_4_3')),
                ('c2_5', models.IntegerField(default=0, verbose_name='Кол2_5')),
                ('c2_5_1', models.IntegerField(default=0, verbose_name='Кол2_5_1')),
                ('c2_5_2', models.IntegerField(default=0, verbose_name='Кол2_5_2')),
                ('c2_5_3', models.IntegerField(default=0, verbose_name='Кол2_5_3')),
                ('c2_5_4', models.IntegerField(default=0, verbose_name='Кол2_5_4')),
                ('c2_5_5', models.IntegerField(default=0, verbose_name='Кол2_5_5')),
                ('c2_5_6', models.IntegerField(default=0, verbose_name='Кол2_5_6')),
                ('c2_5_7', models.IntegerField(default=0, verbose_name='Кол2_5_7')),
                ('c2_5_8', models.IntegerField(default=0, verbose_name='Кол2_5_8')),
                ('c2_5_9', models.IntegerField(default=0, verbose_name='Кол2_5_9')),
                ('c2_5_10', models.IntegerField(default=0, verbose_name='Кол2_5_10')),
                ('c2_5_11', models.IntegerField(default=0, verbose_name='Кол2_5_11')),
                ('c2_5_12', models.IntegerField(default=0, verbose_name='Кол2_5_12')),
                ('c2_5_13', models.IntegerField(default=0, verbose_name='Кол2_5_13')),
                ('c2_5_14', models.IntegerField(default=0, verbose_name='Кол2_5_14')),
                ('c2_5_15', models.IntegerField(default=0, verbose_name='Кол2_5_15')),
                ('c2_5_16', models.IntegerField(default=0, verbose_name='Кол2_5_16')),
                ('c2_5_17', models.IntegerField(default=0, verbose_name='Кол2_5_17')),
                ('c2_5_18', models.IntegerField(default=0, verbose_name='Кол2_5_18')),
                ('c2_5_19', models.IntegerField(default=0, verbose_name='Кол2_5_19')),
                ('c2_5_20', models.IntegerField(default=0, verbose_name='Кол2_5_20')),
                ('c2_5_21', models.IntegerField(default=0, verbose_name='Кол2_5_21')),
                ('c2_5_22', models.IntegerField(default=0, verbose_name='Кол2_5_22')),
                ('c2_5_23', models.IntegerField(default=0, verbose_name='Кол2_5_23')),
                ('c2_5_24', models.IntegerField(default=0, verbose_name='Кол2_5_24')),
                ('c2_5_25', models.IntegerField(default=0, verbose_name='Кол2_5_25')),
                ('c2_5_26', models.IntegerField(default=0, verbose_name='Кол2_5_26')),
                ('c2_5_27', models.IntegerField(default=0, verbose_name='Кол2_5_27')),
                ('c2_5_28', models.IntegerField(default=0, verbose_name='Кол2_5_28')),
                ('c2_5_29', models.IntegerField(default=0, verbose_name='Кол2_5_29')),
                ('c2_5_30', models.IntegerField(default=0, verbose_name='Кол2_5_30')),
                ('c2_5_31', models.IntegerField(default=0, verbose_name='Кол2_5_31')),
                ('c2_5_32', models.IntegerField(default=0, verbose_name='Кол2_5_32')),
                ('c2_5_33', models.IntegerField(default=0, verbose_name='Кол2_5_33')),
                ('c2_5_34', models.IntegerField(default=0, verbose_name='Кол2_5_34')),
                ('c2_5_35', models.IntegerField(default=0, verbose_name='Кол2_5_35')),
                ('c2_5_36', models.IntegerField(default=0, verbose_name='Кол2_5_36')),
                ('c2_5_37', models.IntegerField(default=0, verbose_name='Кол2_5_37')),
                ('c2_5_38', models.IntegerField(default=0, verbose_name='Кол2_5_38')),
                ('c2_5_39', models.IntegerField(default=0, verbose_name='Кол2_5_39')),
                ('c2_5_40', models.IntegerField(default=0, verbose_name='Кол2_5_40')),
                ('c2_5_41', models.IntegerField(default=0, verbose_name='Кол2_5_41')),
                ('c2_6', models.IntegerField(default=0, verbose_name='Кол2_6')),
                ('c2_7', models.IntegerField(default=0, verbose_name='Кол2_7')),
                ('c2_8', models.IntegerField(default=0, verbose_name='Кол2_8')),
                ('c2_9', models.IntegerField(default=0, verbose_name='Кол2_9')),
                ('c2_10', models.IntegerField(default=0, verbose_name='Кол2_10')),
                ('c2_11', models.IntegerField(default=0, verbose_name='Кол2_11')),
                ('c2_12', models.IntegerField(default=0, verbose_name='Кол2_12')),
                ('c2_13', models.IntegerField(default=0, verbose_name='Кол2_13')),
                ('c2_13_1', models.IntegerField(default=0, verbose_name='Кол2_13_1')),
                ('c2_13_2', models.IntegerField(default=0, verbose_name='Кол2_13_2')),
                ('c2_13_3', models.IntegerField(default=0, verbose_name='Кол2_13_3')),
                ('c2_13_4', models.IntegerField(default=0, verbose_name='Кол2_13_4')),
                ('c2_13_5', models.IntegerField(default=0, verbose_name='Кол2_13_5')),
                ('c2_13_6', models.IntegerField(default=0, verbose_name='Кол2_13_6')),
                ('c2_13_7', models.IntegerField(default=0, verbose_name='Кол2_13_7')),
                ('c2_13_8', models.IntegerField(default=0, verbose_name='Кол2_13_8')),
                ('c2_13_9', models.IntegerField(default=0, verbose_name='Кол2_13_9')),
                ('c2_13_10', models.IntegerField(default=0, verbose_name='Кол2_13_10')),
                ('c2_13_11', models.IntegerField(default=0, verbose_name='Кол2_13_11')),
                ('c2_13_12', models.IntegerField(default=0, verbose_name='Кол2_13_12')),
                ('c2_13_13', models.IntegerField(default=0, verbose_name='Кол2_13_13')),
                ('c2_13_14', models.IntegerField(default=0, verbose_name='Кол2_13_14')),
                ('c2_13_15', models.IntegerField(default=0, verbose_name='Кол2_13_15')),
                ('c2_13_16', models.IntegerField(default=0, verbose_name='Кол2_13_16')),
                ('c2_13_17', models.IntegerField(default=0, verbose_name='Кол2_13_17')),
                ('c2_13_18', models.IntegerField(default=0, verbose_name='Кол2_13_18')),
                ('c2_13_19', models.IntegerField(default=0, verbose_name='Кол2_13_19')),
                ('c2_13_20', models.IntegerField(default=0, verbose_name='Кол2_13_20')),
                ('c2_13_21', models.IntegerField(default=0, verbose_name='Кол2_13_21')),
                ('c2_13_22', models.IntegerField(default=0, verbose_name='Кол2_13_22')),
                ('c2_13_23', models.IntegerField(default=0, verbose_name='Кол2_13_23')),
                ('c2_13_24', models.IntegerField(default=0, verbose_name='Кол2_13_24')),
                ('c2_13_25', models.IntegerField(default=0, verbose_name='Кол2_13_25')),
                ('c2_13_26', models.IntegerField(default=0, verbose_name='Кол2_13_26')),
                ('c2_13_27', models.IntegerField(default=0, verbose_name='Кол2_13_27')),
                ('c2_13_28', models.IntegerField(default=0, verbose_name='Кол2_13_28')),
                ('c2_13_29', models.IntegerField(default=0, verbose_name='Кол2_13_29')),
                ('c2_13_30', models.IntegerField(default=0, verbose_name='Кол2_13_30')),
                ('c2_13_31', models.IntegerField(default=0, verbose_name='Кол2_13_31')),
                ('c2_13_32', models.IntegerField(default=0, verbose_name='Кол2_13_32')),
                ('c2_13_33', models.IntegerField(default=0, verbose_name='Кол2_13_33')),
                ('c2_13_34', models.IntegerField(default=0, verbose_name='Кол2_13_34')),
                ('c2_13_35', models.IntegerField(default=0, verbose_name='Кол2_13_35')),
                ('c2_13_36', models.IntegerField(default=0, verbose_name='Кол2_13_36')),
                ('c2_13_37', models.IntegerField(default=0, verbose_name='Кол2_13_37')),
                ('c2_13_38', models.IntegerField(default=0, verbose_name='Кол2_13_38')),
                ('c2_13_39', models.IntegerField(default=0, verbose_name='Кол2_13_39')),
                ('c2_13_40', models.IntegerField(default=0, verbose_name='Кол2_13_40')),
                ('c2_13_41', models.IntegerField(default=0, verbose_name='Кол2_13_41')),
                ('c2_13_42', models.IntegerField(default=0, verbose_name='Кол2_13_42')),
                ('c2_13_43', models.IntegerField(default=0, verbose_name='Кол2_13_43')),
                ('c2_13_44', models.IntegerField(default=0, verbose_name='Кол2_13_44')),
                ('c2_13_45', models.IntegerField(default=0, verbose_name='Кол2_13_45')),
                ('c2_13_46', models.IntegerField(default=0, verbose_name='Кол2_13_46')),
                ('c2_13_47', models.IntegerField(default=0, verbose_name='Кол2_13_47')),
                ('c2_13_48', models.IntegerField(default=0, verbose_name='Кол2_13_48')),
                ('c2_13_49', models.IntegerField(default=0, verbose_name='Кол2_13_49')),
                ('c2_13_50', models.IntegerField(default=0, verbose_name='Кол2_13_50')),
                ('c2_13_51', models.IntegerField(default=0, verbose_name='Кол2_13_51')),
                ('c2_13_52', models.IntegerField(default=0, verbose_name='Кол2_13_52')),
                ('c2_13_53', models.IntegerField(default=0, verbose_name='Кол2_13_53')),
                ('c2_13_54', models.IntegerField(default=0, verbose_name='Кол2_13_54')),
                ('c2_13_55', models.IntegerField(default=0, verbose_name='Кол2_13_55')),
                ('c2_13_56', models.IntegerField(default=0, verbose_name='Кол2_13_56')),
                ('c2_13_57', models.IntegerField(default=0, verbose_name='Кол2_13_57')),
                ('c2_13_58', models.IntegerField(default=0, verbose_name='Кол2_13_58')),
                ('c2_13_59', models.IntegerField(default=0, verbose_name='Кол2_13_59')),
                ('c2_13_60', models.IntegerField(default=0, verbose_name='Кол2_13_60')),
                ('c2_13_61', models.IntegerField(default=0, verbose_name='Кол2_13_61')),
                ('c2_13_62', models.IntegerField(default=0, verbose_name='Кол2_13_62')),
                ('c2_13_63', models.IntegerField(default=0, verbose_name='Кол2_13_63')),
                ('c2_13_64', models.IntegerField(default=0, verbose_name='Кол2_13_64')),
                ('c2_13_65', models.IntegerField(default=0, verbose_name='Кол2_13_65')),
                ('c2_13_66', models.IntegerField(default=0, verbose_name='Кол2_13_66')),
                ('c2_13_67', models.IntegerField(default=0, verbose_name='Кол2_13_67')),
                ('c2_13_68', models.IntegerField(default=0, verbose_name='Кол2_13_68')),
                ('c2_13_69', models.IntegerField(default=0, verbose_name='Кол2_13_69')),
                ('c2_13_70', models.IntegerField(default=0, verbose_name='Кол2_13_70')),
                ('c2_13_71', models.IntegerField(default=0, verbose_name='Кол2_13_71')),
                ('c2_13_72', models.IntegerField(default=0, verbose_name='Кол2_13_72')),
                ('c2_13_73', models.IntegerField(default=0, verbose_name='Кол2_13_73')),
                ('c2_13_74', models.IntegerField(default=0, verbose_name='Кол2_13_74')),
                ('c2_13_75', models.IntegerField(default=0, verbose_name='Кол2_13_75')),
                ('c2_13_76', models.IntegerField(default=0, verbose_name='Кол2_13_76')),
                ('c2_13_77', models.IntegerField(default=0, verbose_name='Кол2_13_77')),
                ('c2_13_78', models.IntegerField(default=0, verbose_name='Кол2_13_78')),
                ('c2_13_79', models.IntegerField(default=0, verbose_name='Кол2_13_79')),
                ('c2_13_80', models.IntegerField(default=0, verbose_name='Кол2_13_80')),
                ('c2_13_81', models.IntegerField(default=0, verbose_name='Кол2_13_81')),
                ('c2_13_82', models.IntegerField(default=0, verbose_name='Кол2_13_82')),
                ('c2_13_83', models.IntegerField(default=0, verbose_name='Кол2_13_83')),
                ('c2_13_84', models.IntegerField(default=0, verbose_name='Кол2_13_84')),
                ('c2_13_85', models.IntegerField(default=0, verbose_name='Кол2_13_85')),
                ('c2_13_86', models.IntegerField(default=0, verbose_name='Кол2_13_86')),
                ('c2_13_87', models.IntegerField(default=0, verbose_name='Кол2_13_87')),
                ('c2_13_88', models.IntegerField(default=0, verbose_name='Кол2_13_88')),
                ('c2_13_89', models.IntegerField(default=0, verbose_name='Кол2_13_89')),
                ('c2_13_90', models.IntegerField(default=0, verbose_name='Кол2_13_90')),
                ('c2_13_91', models.IntegerField(default=0, verbose_name='Кол2_13_91')),
                ('c2_13_92', models.IntegerField(default=0, verbose_name='Кол2_13_92')),
                ('c2_13_93', models.IntegerField(default=0, verbose_name='Кол2_13_93')),
                ('c2_13_94', models.IntegerField(default=0, verbose_name='Кол2_13_94')),
                ('c2_13_95', models.IntegerField(default=0, verbose_name='Кол2_13_95')),
                ('c2_13_96', models.IntegerField(default=0, verbose_name='Кол2_13_96')),
                ('c2_13_97', models.IntegerField(default=0, verbose_name='Кол2_13_97')),
                ('c2_13_98', models.IntegerField(default=0, verbose_name='Кол2_13_98')),
                ('c2_13_99', models.IntegerField(default=0, verbose_name='Кол2_13_99')),
                ('c2_13_100', models.IntegerField(default=0, verbose_name='Кол2_13_100')),
                ('c2_13_101', models.IntegerField(default=0, verbose_name='Кол2_13_101')),
                ('c2_13_102', models.IntegerField(default=0, verbose_name='Кол2_13_102')),
                ('c2_13_103', models.IntegerField(default=0, verbose_name='Кол2_13_103')),
                ('c2_13_104', models.IntegerField(default=0, verbose_name='Кол2_13_104')),
                ('c2_13_105', models.IntegerField(default=0, verbose_name='Кол2_13_105')),
                ('c2_13_106', models.IntegerField(default=0, verbose_name='Кол2_13_106')),
                ('c2_13_107', models.IntegerField(default=0, verbose_name='Кол2_13_107')),
                ('c2_13_108', models.IntegerField(default=0, verbose_name='Кол2_13_108')),
                ('c2_13_109', models.IntegerField(default=0, verbose_name='Кол2_13_109')),
                ('c2_13_110', models.IntegerField(default=0, verbose_name='Кол2_13_110')),
                ('c2_13_111', models.IntegerField(default=0, verbose_name='Кол2_13_111')),
                ('c2_13_112', models.IntegerField(default=0, verbose_name='Кол2_13_112')),
                ('c2_13_113', models.IntegerField(default=0, verbose_name='Кол2_13_113')),
                ('c2_13_114', models.IntegerField(default=0, verbose_name='Кол2_13_114')),
                ('c2_13_115', models.IntegerField(default=0, verbose_name='Кол2_13_115')),
                ('c2_13_116', models.IntegerField(default=0, verbose_name='Кол2_13_116')),
                ('c2_13_117', models.IntegerField(default=0, verbose_name='Кол2_13_117')),
                ('c2_13_118', models.IntegerField(default=0, verbose_name='Кол2_13_118')),
                ('c2_13_119', models.IntegerField(default=0, verbose_name='Кол2_13_119')),
                ('c2_13_120', models.IntegerField(default=0, verbose_name='Кол2_13_120')),
                ('c2_13_121', models.IntegerField(default=0, verbose_name='Кол2_13_121')),
                ('c2_13_122', models.IntegerField(default=0, verbose_name='Кол2_13_122')),
                ('c2_13_123', models.IntegerField(default=0, verbose_name='Кол2_13_123')),
                ('c2_13_124', models.IntegerField(default=0, verbose_name='Кол2_13_124')),
                ('c2_14', models.IntegerField(default=0, verbose_name='Кол2_14')),
                ('c2_14_1', models.IntegerField(default=0, verbose_name='Кол2_14_1')),
                ('c2_14_2', models.IntegerField(default=0, verbose_name='Кол2_14_2')),
                ('c2_14_3', models.IntegerField(default=0, verbose_name='Кол2_14_3')),
                ('c2_14_4', models.IntegerField(default=0, verbose_name='Кол2_14_4')),
                ('c2_14_5', models.IntegerField(default=0, verbose_name='Кол2_14_5')),
                ('c2_14_6', models.IntegerField(default=0, verbose_name='Кол2_14_6')),
                ('c2_14_7', models.IntegerField(default=0, verbose_name='Кол2_14_7')),
                ('c2_14_8', models.IntegerField(default=0, verbose_name='Кол2_14_8')),
                ('c2_14_9', models.IntegerField(default=0, verbose_name='Кол2_14_9')),
                ('c2_14_10', models.IntegerField(default=0, verbose_name='Кол2_14_10')),
                ('c2_14_11', models.IntegerField(default=0, verbose_name='Кол2_14_11')),
                ('c2_14_12', models.IntegerField(default=0, verbose_name='Кол2_14_12')),
                ('c2_14_13', models.IntegerField(default=0, verbose_name='Кол2_14_13')),
                ('c2_14_14', models.IntegerField(default=0, verbose_name='Кол2_14_14')),
                ('c2_14_15', models.IntegerField(default=0, verbose_name='Кол2_14_15')),
                ('c2_14_16', models.IntegerField(default=0, verbose_name='Кол2_14_16')),
                ('c2_14_17', models.IntegerField(default=0, verbose_name='Кол2_14_17')),
                ('c2_14_18', models.IntegerField(default=0, verbose_name='Кол2_14_18')),
                ('c2_14_19', models.IntegerField(default=0, verbose_name='Кол2_14_19')),
                ('c2_14_20', models.IntegerField(default=0, verbose_name='Кол2_14_20')),
                ('c2_14_21', models.IntegerField(default=0, verbose_name='Кол2_14_21')),
                ('c2_14_22', models.IntegerField(default=0, verbose_name='Кол2_14_22')),
                ('c2_14_23', models.IntegerField(default=0, verbose_name='Кол2_14_23')),
                ('c2_14_24', models.IntegerField(default=0, verbose_name='Кол2_14_24')),
                ('c2_14_25', models.IntegerField(default=0, verbose_name='Кол2_14_25')),
                ('c2_14_26', models.IntegerField(default=0, verbose_name='Кол2_14_26')),
                ('c2_14_27', models.IntegerField(default=0, verbose_name='Кол2_14_27')),
                ('c2_14_28', models.IntegerField(default=0, verbose_name='Кол2_14_28')),
                ('c2_14_29', models.IntegerField(default=0, verbose_name='Кол2_14_29')),
                ('c2_14_30', models.IntegerField(default=0, verbose_name='Кол2_14_30')),
                ('c2_14_31', models.IntegerField(default=0, verbose_name='Кол2_14_31')),
                ('c2_14_32', models.IntegerField(default=0, verbose_name='Кол2_14_32')),
                ('c2_14_33', models.IntegerField(default=0, verbose_name='Кол2_14_33')),
                ('c2_14_34', models.IntegerField(default=0, verbose_name='Кол2_14_34')),
                ('c2_14_35', models.IntegerField(default=0, verbose_name='Кол2_14_35')),
                ('c2_14_36', models.IntegerField(default=0, verbose_name='Кол2_14_36')),
                ('c2_14_37', models.IntegerField(default=0, verbose_name='Кол2_14_37')),
                ('c2_14_38', models.IntegerField(default=0, verbose_name='Кол2_14_38')),
                ('c2_14_39', models.IntegerField(default=0, verbose_name='Кол2_14_39')),
                ('c2_14_40', models.IntegerField(default=0, verbose_name='Кол2_14_40')),
                ('c2_14_41', models.IntegerField(default=0, verbose_name='Кол2_14_41')),
                ('c2_14_42', models.IntegerField(default=0, verbose_name='Кол2_14_42')),
                ('c2_14_43', models.IntegerField(default=0, verbose_name='Кол2_14_43')),
                ('c2_14_44', models.IntegerField(default=0, verbose_name='Кол2_14_44')),
                ('c2_14_45', models.IntegerField(default=0, verbose_name='Кол2_14_45')),
                ('c2_15', models.IntegerField(default=0, verbose_name='Кол2_15')),
                ('c2_16', models.IntegerField(default=0, verbose_name='Кол2_16')),
                ('c2_17', models.IntegerField(default=0, verbose_name='Кол2_17')),
                ('c2_18', models.IntegerField(default=0, verbose_name='Кол2_18')),
                ('c2_19', models.IntegerField(default=0, verbose_name='Кол2_19')),
                ('c2_20', models.IntegerField(default=0, verbose_name='Кол2_20')),
                ('c2_21', models.IntegerField(default=0, verbose_name='Кол2_21')),
                ('c2_22', models.IntegerField(default=0, verbose_name='Кол2_22')),
                ('c2_23', models.IntegerField(default=0, verbose_name='Кол2_23')),
                ('c2_24', models.IntegerField(default=0, verbose_name='Кол2_24')),
                ('c2_25', models.IntegerField(default=0, verbose_name='Кол2_25')),
                ('c2_26', models.IntegerField(default=0, verbose_name='Кол2_26')),
                ('c2_27', models.IntegerField(default=0, verbose_name='Кол2_27')),
                ('c2_28', models.IntegerField(default=0, verbose_name='Кол2_28')),
                ('c3_1', models.IntegerField(default=0, verbose_name='Кол3_1')),
                ('c3_2', models.IntegerField(default=0, verbose_name='Кол3_2')),
                ('c3_3', models.IntegerField(default=0, verbose_name='Кол3_3')),
                ('c3_4', models.IntegerField(default=0, verbose_name='Кол3_4')),
                ('c3_5', models.IntegerField(default=0, verbose_name='Кол3_5')),
                ('c3_6', models.IntegerField(default=0, verbose_name='Кол3_6')),
                ('c3_7', models.IntegerField(default=0, verbose_name='Кол3_7')),
                ('c3_8', models.IntegerField(default=0, verbose_name='Кол3_8')),
                ('c3_9', models.IntegerField(default=0, verbose_name='Кол3_9')),
                ('c3_10', models.IntegerField(default=0, verbose_name='Кол3_10')),
                ('c3_11', models.IntegerField(default=0, verbose_name='Кол3_11')),
                ('c3_12', models.IntegerField(default=0, verbose_name='Кол3_12')),
                ('c3_13', models.IntegerField(default=0, verbose_name='Кол3_13')),
                ('c3_14', models.IntegerField(default=0, verbose_name='Кол3_14')),
                ('c3_15', models.IntegerField(default=0, verbose_name='Кол3_15')),
                ('c3_16', models.IntegerField(default=0, verbose_name='Кол3_16')),
                ('c3_17', models.IntegerField(default=0, verbose_name='Кол3_17')),
                ('c3_18', models.IntegerField(default=0, verbose_name='Кол3_18')),
                ('c3_19', models.IntegerField(default=0, verbose_name='Кол3_19')),
                ('c3_20', models.IntegerField(default=0, verbose_name='Кол3_20')),
                ('c3_21', models.IntegerField(default=0, verbose_name='Кол3_21')),
                ('c3_22', models.IntegerField(default=0, verbose_name='Кол3_22')),
                ('c3_23', models.IntegerField(default=0, verbose_name='Кол3_23')),
                ('c3_24', models.IntegerField(default=0, verbose_name='Кол3_24')),
                ('c3_25', models.IntegerField(default=0, verbose_name='Кол3_25')),
                ('c3_26', models.IntegerField(default=0, verbose_name='Кол3_26')),
                ('c3_27', models.IntegerField(default=0, verbose_name='Кол3_27')),
                ('c3_28', models.IntegerField(default=0, verbose_name='Кол3_28')),
                ('c3_29', models.IntegerField(default=0, verbose_name='Кол3_29')),
                ('c3_30', models.IntegerField(default=0, verbose_name='Кол3_30')),
                ('c3_31', models.IntegerField(default=0, verbose_name='Кол3_31')),
                ('c3_32', models.IntegerField(default=0, verbose_name='Кол3_32')),
                ('c3_33', models.IntegerField(default=0, verbose_name='Кол3_33')),
                ('c3_34', models.IntegerField(default=0, verbose_name='Кол3_34')),
                ('c3_35', models.IntegerField(default=0, verbose_name='Кол3_35')),
                ('c3_36', models.IntegerField(default=0, verbose_name='Кол3_36')),
                ('c3_37', models.IntegerField(default=0, verbose_name='Кол3_37')),
                ('c3_38', models.IntegerField(default=0, verbose_name='Кол3_38')),
                ('c4_1', models.IntegerField(default=0, verbose_name='Кол4_1')),
                ('c4_2', models.IntegerField(default=0, verbose_name='Кол4_2')),
                ('c4_3', models.IntegerField(default=0, verbose_name='Кол4_3')),
                ('c4_4', models.IntegerField(default=0, verbose_name='Кол4_4')),
                ('c4_5', models.IntegerField(default=0, verbose_name='Кол4_5')),
                ('c4_6', models.IntegerField(default=0, verbose_name='Кол4_6')),
                ('c4_7', models.IntegerField(default=0, verbose_name='Кол4_7')),
                ('c4_8', models.IntegerField(default=0, verbose_name='Кол4_8')),
                ('c4_9', models.IntegerField(default=0, verbose_name='Кол4_9')),
                ('c4_10', models.IntegerField(default=0, verbose_name='Кол4_10')),
                ('c4_11', models.IntegerField(default=0, verbose_name='Кол4_11')),
                ('c4_12', models.IntegerField(default=0, verbose_name='Кол4_12')),
                ('c4_13', models.IntegerField(default=0, verbose_name='Кол4_13')),
                ('c4_14', models.IntegerField(default=0, verbose_name='Кол4_14')),
                ('c4_15', models.IntegerField(default=0, verbose_name='Кол4_15')),
            ],
            options={
            },
            bases=('medicament.document',),
        ),
        migrations.CreateModel(
            name='Doc1',
            fields=[
                ('document_ptr', models.OneToOneField(serialize=False, primary_key=True, auto_created=True, to='medicament.Document', parent_link=True)),
                ('c1_1', models.IntegerField(default=0, verbose_name='Кол1-1')),
                ('c1_2', models.IntegerField(default=0, verbose_name='Кол1-2')),
                ('c1_3', models.IntegerField(default=0, verbose_name='Кол1-3')),
                ('c1_4', models.IntegerField(default=0, verbose_name='Кол1-4')),
                ('c1_5', models.IntegerField(default=0, verbose_name='Кол1-5')),
                ('c2_6', models.IntegerField(default=0, verbose_name='Кол2-6')),
                ('c2_7', models.IntegerField(default=0, verbose_name='Кол2-7')),
                ('c2_8', models.IntegerField(default=0, verbose_name='Кол2-8')),
                ('c3_1', models.IntegerField(default=0, verbose_name='КолПр3-1')),
                ('c3_2', models.IntegerField(default=0, verbose_name='КолПр3-2')),
                ('c3_3', models.IntegerField(default=0, verbose_name='КолПр3-3')),
                ('c3_4', models.IntegerField(default=0, verbose_name='КолПр3-4')),
                ('c3_5', models.IntegerField(default=0, verbose_name='КолПр3-5')),
                ('c3_6', models.IntegerField(default=0, verbose_name='КолПр3-6')),
                ('c3_7', models.IntegerField(default=0, verbose_name='КолПр3-7')),
                ('c3_8', models.IntegerField(default=0, verbose_name='КолПр3-8')),
                ('c4_1', models.IntegerField(default=0, verbose_name='Кол4-1')),
                ('c4_2', models.IntegerField(default=0, verbose_name='Кол4-2')),
                ('c4_3', models.IntegerField(default=0, verbose_name='Кол4-3')),
                ('c4_4', models.IntegerField(default=0, verbose_name='Кол4-4')),
                ('c4_5', models.IntegerField(default=0, verbose_name='Кол4-5')),
                ('c4_6', models.IntegerField(default=0, verbose_name='Кол4-6')),
                ('c4_7', models.IntegerField(default=0, verbose_name='Кол4-7')),
                ('c4_8', models.IntegerField(default=0, verbose_name='Кол4-8')),
            ],
            options={
            },
            bases=('medicament.document',),
        ),
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование Краткое')),
                ('name_full', models.CharField(max_length=255, verbose_name='Наименование Полное')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('dateb', models.DateField()),
                ('datee', models.DateField()),
                ('prev', models.ForeignKey(null=True, to='medicament.Period', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Регион')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('Р', 'Редактирование'), ('К', 'Контроль')], max_length=1, default='Р', verbose_name='Роль')),
                ('hosp', models.ForeignKey(to='medicament.Hosp')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='hosp',
            name='region',
            field=models.ForeignKey(null=True, to='medicament.Region', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='document',
            name='hosp',
            field=models.ForeignKey(to='medicament.Hosp'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='document',
            name='period',
            field=models.ForeignKey(to='medicament.Period'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='doc_hosp',
            name='doc_type',
            field=models.ForeignKey(to='medicament.Doc_type'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='doc_hosp',
            name='hosp',
            field=models.ForeignKey(to='medicament.Hosp'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(to='medicament.Document'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
